template: true
valuesFilePath: values.yml

pipelines:
  - name: {{ .Values.MicroPipeline.name }}
    steps:
      - name: {{ .Values.MicroPipeline.step.name }}
        type: {{ .Values.MicroPipeline.step.type | default "Bash" }}
        {{- if .Values.MicroPipeline.step.execution }}
        execution: {{ .Values.MicroPipeline.step.execution }}
        {{- end }}
