template: true
valuesFilePath: values.yml

pipelines:
  - name: {{ .Values.MicroPipeline.name | default "Pipeline" }}
    steps:
      - name: {{ .Values.MicroPipeline.step.name | default "PipelineStep" }}
        type: {{ .Values.MicroPipeline.step.type | default "Bash" }}
        execution: {{ .Values.MicroPipeline.step.execution }}
