template: true
valuesFilePath: values.yml

pipelines:
  - name: {{ .Values.MicroPipeline.name }}
    steps:
      - name: {{ .Values.MicroPipeline.step.name }}
        type: {{ .Values.MicroPipeline.step.type | default "Bash" }}
        execution:
        {{- if .Values.MicroPipeline.step.execution.onExecute }}
          onExecute:
            {{ .Values.MicroPipeline.step.execution.onExecute }}
        {{- end }}
